// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2, arg3) {
  return window['go']['spgui']['SPGUI']['AddItem'](arg1, arg2, arg3);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['spgui']['SPGUI']['DeleteItem'](arg1, arg2);
}

export function GetItem(arg1, arg2, arg3) {
  return window['go']['spgui']['SPGUI']['GetItem'](arg1, arg2, arg3);
}

export function JSON(arg1) {
  return window['go']['spgui']['SPGUI']['JSON'](arg1);
}

export function ListItems(arg1) {
  return window['go']['spgui']['SPGUI']['ListItems'](arg1);
}

export function OpenConfigDialog() {
  return window['go']['spgui']['SPGUI']['OpenConfigDialog']();
}

export function Ping() {
  return window['go']['spgui']['SPGUI']['Ping']();
}

export function SetConfig(arg1) {
  return window['go']['spgui']['SPGUI']['SetConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['spgui']['SPGUI']['SetContext'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['spgui']['SPGUI']['UpdateItem'](arg1, arg2, arg3, arg4);
}
