// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spgui} from '../models';
import {context} from '../models';

export function AddItem(arg1:string,arg2:Record<string, any>,arg3:string):Promise<Record<string, any>>;

export function DeleteItem(arg1:string,arg2:number):Promise<boolean>;

export function GetItem(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function JSON(arg1:any):Promise<string>;

export function ListItems(arg1:spgui.ListQuery):Promise<spgui.ListResponse>;

export function OpenConfigDialog():Promise<string>;

export function Ping():Promise<string>;

export function SetConfig(arg1:spgui.Config):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateItem(arg1:string,arg2:number,arg3:Record<string, any>,arg4:string):Promise<Record<string, any>>;
